name: Bin Day Reminder

on:
  schedule:
    # Run every Tuesday at 07:00 UTC (8:00am UK time during summer)
    - cron: "0 7 * * TUE"
  workflow_dispatch:  # still lets you trigger it manually

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install puppeteer nodemailer

      - name: Run script
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: node bin-reminder.js
